weights: /public1/xinyu/CohesinProject/DeepLearning_Cohesin/Loading_domain_yolo/yolov5x.pt
cfg: /public1/xinyu/CohesinProject/DeepLearning_Cohesin/Loading_domain_yolo/models/accModels/yolov5xP2.yaml
data: /public1/xinyu/CohesinProject/DeepLearning_Cohesin/Loading_domain_yolo/data/LoadingDomain.yaml
hyp: /public1/xinyu/CohesinProject/DeepLearning_Cohesin/Loading_domain_yolo/data/hyps/hyp.scratch.yaml
epochs: 300
batch_size: 16
imgsz: 480
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: '1'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 8
project: /public1/xinyu/CohesinProject/DeepLearning_Cohesin/Loading_domain_yolo/runs/train
name: LoadingDomain.V6
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.5
patience: 100
freeze: 0
save_period: -1
local_rank: -1
nohalf: false
quantize: false
BackendType: Tensorrt
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
sparse: false
sparse_rate: 0.001
save_dir: /public1/xinyu/CohesinProject/DeepLearning_Cohesin/Loading_domain_yolo/runs/train/LoadingDomain.V6
